[server]
headless = true
maxUploadSize = 10
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#e99a26"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f6f8"
textColor = "#172b3a"
font = "sans serif"

